import { Article } from "@/components/Article";
import { Example } from "@/components/Example";
import { Callout } from "@/components/Callout";

export const metadata = {
  title: "word classes — kawaba",
};

export default function KawabaWordClasses() {
  return (
    <Article>
      <h1>word classes</h1>
      <p>
        Every lexical word in Kawaba carries an obligatory <strong>word class</strong> prefix, a single 
        vowel attached to the front of the word that marks which grammatical category the 
        word belongs to.
      </p>
      <p>
        There are five word-class prefixes, one for each vowel: 
      </p>
      <table>
        <thead>
          <tr>
            <th scope="col">prefix</th>
            <th scope="col">word class</th>
            <th scope="col">function</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>a-</td>
            <td>noun</td>
            <td>expresses a person, place, thing, state, or concept</td>
          </tr>
          <tr>
            <td>e-</td>
            <td>qualifier</td>
            <td>expresses a quality or property</td>
          </tr>
          <tr>
            <td>i-</td>
            <td>verb</td>
            <td>expresses an action, event, process, or state</td>
          </tr>
          <tr>
            <td>o-</td>
            <td>numeral</td>
            <td>expresses a numerical quantity</td>
          </tr>
          <tr>
            <td>u-</td>
            <td>circumstantial</td>
            <td>expresses place, time, degree, or frequency</td>
          </tr>
        </tbody>
      </table>
      <p>
        A word in Kawaba can be used as any of the five classes by changing its prefix, 
        allowing flexibility in word derivation from a very small root inventory.
      </p>
      <div className="flex flex-row gap-4">
        <Example
          kawaba="aba"
          gloss="N-part"
          translation="part"
        />
        <Example
          kawaba="eba"
          gloss="Q-part"
          translation="partial"
        />  
        <Example
          kawaba="iba"
          gloss="V-part"
          translation="to divide"
        />
        <Example
          kawaba="oba"
          gloss="NUM-part"
          translation="one"
        />
        <Example
          kawaba="uba"
          gloss="C-part"
          translation="partially"
        />             
      </div>
      <Callout>
        <p>
          While the other word classes derive their meaning from the lexical content of 
          the word they attach to, the numeral class is the odd one out. Numeral words 
          are generated by a separate coercion system that assigns the phonetic content 
          of a word to a numeric value, independent of what the word actually means. 
          The mechanics of this coercion system are covered in the Numbers section.
        </p>
      </Callout>
    </Article>
  );
}
